name: build-cache
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  build-cache:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/app
    steps:
      - uses: actions/checkout@v4
        with:
          path: generator-jhipster-native
          fetch-depth: 1
      - uses: jhipster/actions/setup-runner@v0
        with:
          node-version: 20
          binary-dir: ${{ github.workspace }}/generator-jhipster-native/cli/
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: 17
          distribution: 'graalvm-community'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: jhipster/actions/cache-npm-dependencies@v0
        with:
          generator-path: generator-jhipster-native
        if: always()
      - run: cli.cjs generate-sample --all
        continue-on-error: true
      - run: cd mvcJwt && ./npmw
        continue-on-error: true
      - run: npm run backend:build-cache --workspaces
        continue-on-error: true
      - uses: jhipster/actions/create-app-path@v0
      - run: cli.cjs generate-sample --all --build gradle
        continue-on-error: true
      - run: cd mvcJwt && ./npmw
        continue-on-error: true
      - run: npm run backend:build-cache --workspaces
        continue-on-error: true
      - uses: jhipster/actions/save-cache@v0
        if: always()
        with:
          key: ${{ github.run_id }}
          npm: true
          maven: true
          gradle: true
      - uses: jhipster/actions/restore-cache@v0
        with:
          npm: true
          maven: true
          gradle: true
