name: JDL tests
concurrency:
  # Group PRs by head_ref, push to main branch by commit id, and others branch by ref.
  group: ${{ github.workflow }}-${{ github.head_ref || (github.ref == 'refs/heads/main' && github.sha) || github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'generators/ci-cd/**'
  pull_request:
    types: [closed, opened, synchronize, reopened]
    branches:
      - '*'
    paths-ignore:
      - 'generators/ci-cd/**'
permissions:
  contents: read
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - id: build
        run: |
          npm ci --ignore-scripts
          cli/cli.cjs github-build-matrix native
  applications:
    name: ${{ matrix.job-name }}
    runs-on: ${{ matrix.os }}
    needs: build-matrix
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/app
    if: github.event.action != 'closed'
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.build-matrix.outputs.matrix)}}
    steps:
      #----------------------------------------------------------------------
      # Install all tools and check configuration
      #----------------------------------------------------------------------
      - name: 'SETUP: checkout generator-jhipster-native'
        uses: actions/checkout@v4
        with:
          path: generator-jhipster-native
          fetch-depth: 2
      - uses: jhipster/actions/setup-runner@v0
        with:
          node-version: ${{ matrix.node-version }}
          maven-cache: true
          gradle-cache: true
          binary-dir: ${{ github.workspace }}/generator-jhipster-native/cli/
      - name: 'SETUP: install generator-jhister-native'
        run: npm ci --prod
        working-directory: ${{ github.workspace }}/generator-jhipster-native
      - name: 'SETUP: setup graalvm'
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      #----------------------------------------------------------------------
      # Install JHipster and generate project+entities
      #----------------------------------------------------------------------
      - name: 'PROJECT: generate'
        run: cli.cjs generate-sample ${{ matrix.sample }} --build ${{ matrix.build-tool }} --no-insight --skip-commit-hook --skip-jhipster-dependencies --no-cypress-audit --skip-install
        env:
          JHI_PROFILE: ${{ matrix.default-environment }}
      - uses: jhipster/actions/compare-sample@v0
        id: compare
        if: >-
          github.event.pull_request && !contains(github.event.pull_request.labels.*.name, 'pr: disable-compare')
        with:
          generator-path: generator-jhipster-native
          cmd: cli.cjs generate-sample ${{ matrix.sample }} --build ${{ matrix.build-tool }} --no-insight --skip-git --skip-commit-hook --skip-jhipster-dependencies --no-cypress-audit --skip-install
        env:
          JHI_PROFILE: ${{ matrix.default-environment }}

      - name: 'SETUP Windows: force npm to use bash'
        if: runner.os == 'Windows'
        run: |
          echo "script-shell=bash" >.npmrc
          cat .npmrc

      - name: 'SETUP MacOS: load Homebrew cache'
        uses: actions/cache@v4
        if: matrix.os == 'macos-13' && steps.compare.outputs.equals != 'true'
        with:
          path: |
            ~/Library/Caches/Homebrew/downloads/*--Docker.dmg
          key: brew-actions-setup-docker-1.0.11
          restore-keys: brew-actions-setup-docker-
      - uses: douglascamata/setup-docker-macos-action@8d5fa43892aed7eee4effcdea113fd53e4d4bf83
        if: matrix.os == 'macos-13' && steps.compare.outputs.equals != 'true'
        timeout-minutes: 10
      - run: ls ~/Library/Caches/Homebrew/
        if: matrix.os == 'macos-13' && steps.compare.outputs.equals != 'true'

      - run: npm run ci:backend:test
        if: steps.compare.outputs.equals != 'true'
      # Native build is memory intensive, containers should not be started.
      - run: npm run native-package -- ${{ matrix.native-package-extra-args }}
        if: steps.compare.outputs.equals != 'true'
        timeout-minutes: 60
      - run: npm run services:up
        if: matrix.e2e != 'false' && steps.compare.outputs.equals != 'true'
      - run: npm run native-e2e --if-present
        if: matrix.e2e != 'false' && steps.compare.outputs.equals != 'true'
      - name: Dump docker logs
        if: always() && matrix.e2e != 'false' && steps.compare.outputs.equals != 'true'
        uses: jwalton/gh-docker-logs@v2
